# configuration for https://travis-ci.org/bitcoinj/bitcoinj
sudo: false
dist: xenial
language: java
jdk:
  - openjdk8
  - openjdk11
install:
  - sudo apt-get install -y protobuf-compiler
script:
    # excluding wallet-template because of the unreliable JavaFX dependency
  - gradle clean build -x :wallettemplate:compileJava

notifications:
  irc:
    channels: "irc.freenode.net#bitcoinj"
    skip_join: true
